const POINT_DEFAULT = 0;
const BALANCE_DEFAULT = 100000;
const POINT_MINIMUM_RATE = 10000;
const POINT_RETURN_PER_MINIMUM_RATE = 100;
const MINIMUM_POINT_CAN_EXCHANGE = 50;

export {
	POINT_DEFAULT,
	BALANCE_DEFAULT,
	POINT_MINIMUM_RATE,
	POINT_RETURN_PER_MINIMUM_RATE,
	MINIMUM_POINT_CAN_EXCHANGE,
};

